export {default as NavBar} from './Navbar'
export {default as Header} from './Header'
export {default as Footer} from './Footer'
export {default as Body} from './Body'
export {default as EventsContainer} from './EventsContainer'