export {default as WordLeft} from './WordLeft'
export {default as WordRight} from './WordRight'
export {default as Line} from './Line'
export {default as Title} from './Title'
export {default as Card} from './Card'
export {default as AboutUs} from './AboutUs/AboutUs'
export {default as AboutCard} from './AboutUs/AboutCard'
export {default as IndividualTitle} from './IndividualTitle'
// export {default as ScrollToTop} from './ScrollToTop'
